source 'http://rubygems.org'

gem 'motion-cocoapods', '~> 1.4.0'
gem 'motion-prime', '0.9.4'

# add reside menu for sidebar support
gem 'prime_reside_menu', '~> 0.1.4'
gem 'prime_awesome', '~> 0.0.1'

# or add sliding menu for sidebar support
# gem 'prime_sliding_menu', '~> 0.1.5'
