source 'http://rubygems.org'

gem 'motion-cocoapods', '~> 1.4.1'
gem 'motion-prime', '0.9.9.1', path: '../../../motion-prime'

# add reside menu for sidebar support
gem 'prime_reside_menu', '~> 0.1.4'
gem 'prime_awesome', '~> 0.0.2'

# or add sliding menu for sidebar support
# gem 'prime_sliding_menu', '~> 0.1.5'

# Add sliding action cells support to MotionPrime.
# gem 'prime_sliding_action'